/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misVentanas;

/**
 *
 * @author alumno
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    String[][] cuentas = {{"admin", "admin"}, {"gianko", "123456"},{"martita","add"},{"",""}};
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jButtonLoginSalir = new javax.swing.JButton();
        jButtonLoginEntrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelLoginError = new javax.swing.JLabel();
        FondoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 180, 30));
        getContentPane().add(jPasswordFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 180, 30));

        jButtonLoginSalir.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButtonLoginSalir.setText("Salir");
        jButtonLoginSalir.setToolTipText("");
        jButtonLoginSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLoginSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 80, -1));

        jButtonLoginEntrar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButtonLoginEntrar.setText("Entrar");
        jButtonLoginEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLoginEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 80, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre de Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        jLabelLoginError.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabelLoginError.setForeground(new java.awt.Color(255, 153, 153));
        getContentPane().add(jLabelLoginError, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 370, -1));

        FondoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/JE_opt (3).jpg"))); // NOI18N
        getContentPane().add(FondoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonLoginSalirActionPerformed

    private void jButtonLoginEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginEntrarActionPerformed
        //validar los datos de usuario
        String username = jTextFieldUsuario.getText();
        String password = String.valueOf(jPasswordFieldPassword.getPassword());
        String nombre="";
        boolean seLogeo = false;
        for (String[] cuenta : cuentas) {
            if (cuenta[0].equals(username) && cuenta[1].equals(password)) {
                seLogeo = true;
                nombre=cuenta[0];
                break;
            }
        }
        if (seLogeo) {
            jLabelLoginError.setText("Usuario y/o Contraseña Erróneos");
            
            VentanaPrincipal vp= new VentanaPrincipal(nombre);
            vp.setVisible(true);
            this.dispose();
        } else {
            jLabelLoginError.setText("Nombre de usuario o contraseña incorrectos");
        }
    }//GEN-LAST:event_jButtonLoginEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoLogin;
    private javax.swing.JButton jButtonLoginEntrar;
    private javax.swing.JButton jButtonLoginSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelLoginError;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
