/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misVentanas;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import misClases.Mozo;
import misClases.Pedido;
import misClases.Plato;
import misEstructuras.ArrayCola;
import misEstructuras.ListaLEG;
import misEstructuras.NodoLEG;

/**
 *
 * @author alumno
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    ListaLEG<Mozo> listaMozo;
    NodoLEG<Mozo> nodito;
    Mozo refM;
    Mozo mocito;
    DefaultTableModel modelo;
    Pedido pedido;
    static String nombre = "";

    public VentanaPrincipal(String nombre) {
        pedido = new Pedido();
        initComponents();
        String[] titulo = {"NumeroPedido", "Descripcion", "Cantidad", "PrecioUnitario"};
        modelo = new DefaultTableModel(null, titulo);
        jTableVerPedidoXMozo.setModel(modelo);

        this.nombre = nombre;
        jLabelNombreUsuario.setText("");
        jLabelNombreUsuario.setText("<html><body>BIENVENIDO(A)<br>" + this.nombre.toUpperCase());

        this.setSize(this.getPreferredSize());
        this.setLocationRelativeTo(null);

        listaMozo = new ListaLEG<Mozo>();

        RegistroMozo.setSize(RegistroMozo.getPreferredSize());

        VerMozoXExp.setSize(VerMozoXExp.getPreferredSize());

        VerPedidosXMozo.setSize(VerPedidosXMozo.getPreferredSize());

        jFramePedido.setSize(jFramePedido.getPreferredSize());

        ElegirMozo.setSize(ElegirMozo.getPreferredSize());
        MontoRec.setSize(ElegirMozo.getPreferredSize());

        mocito = new Mozo("Baca Llontop", 4);

        Plato p1 = new Plato("Ceviche");
        p1.calcularCantidad();
        p1.asignarPrecio();

        Plato p2 = new Plato("Causa");
        p2.calcularCantidad();
        p2.asignarPrecio();

        Plato p3 = new Plato("Ceviche");
        p3.calcularCantidad();
        p3.asignarPrecio();

        Plato p4 = new Plato("Causa");
        p4.calcularCantidad();
        p4.asignarPrecio();

        Pedido pp = new Pedido();
        pp.agregarPlato(p1);
        pp.agregarPlato(p2);
        pp.agregarPlato(p3);
        pp.agregarPlato(p4);
        pp.calcularMontoPago();

        listaMozo.agregarMozoXApellido(mocito);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegistroMozo = new javax.swing.JFrame();
        jButtonRegistrarMozoSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nameMesero1 = new javax.swing.JLabel();
        nameMesero = new javax.swing.JLabel();
        jTextFieldNombreMozo = new javax.swing.JTextField();
        jTextFieldAñosExperiencia = new javax.swing.JTextField();
        jButtonRegisstrarMozo = new javax.swing.JButton();
        jLabelFondoResgisMozo = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jButtonVerListaMozo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaListado = new javax.swing.JTextArea();
        VerMozoXExp = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jButtonVerMozoXexp = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaVerMozoExp = new javax.swing.JTextArea();
        jButtonRegresarM = new javax.swing.JButton();
        VerPedidosXMozo = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButtonBuscarMozo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVerPedidoXMozo = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaVerListadoPedidos = new javax.swing.JTextArea();
        jButtonVerTodosMozos = new javax.swing.JButton();
        jTextFieldApellidoMozo = new javax.swing.JTextField();
        jComboBoxVerPedidos = new javax.swing.JComboBox<>();
        jButtonVerPlatos = new javax.swing.JButton();
        jButtonRegresarMe = new javax.swing.JButton();
        jFramePedido = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        BoxEnrollado = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        BoxCausa = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        BoxPescado = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        Ceviche = new javax.swing.JLabel();
        BoxPollo = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        Ceviche1 = new javax.swing.JLabel();
        BoxRellena = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        Ceviche2 = new javax.swing.JLabel();
        BoxHuancaina = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        Ceviche3 = new javax.swing.JLabel();
        BoxCeviche = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        Ceviche4 = new javax.swing.JLabel();
        BoxBrasa1 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        Ceviche5 = new javax.swing.JLabel();
        BoxLomo = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        AsignarMozo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ElegirMozo = new javax.swing.JFrame();
        jPanel15 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPaneMozo = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaPedido = new javax.swing.JTextArea();
        jButtonGuardarPedido = new javax.swing.JButton();
        MontoRec = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jButtonVerMontoRecaudacion = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextAreaListadoMontoRec = new javax.swing.JTextArea();
        jButtonRegresar = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jButtonRegistrarMozo = new javax.swing.JButton();
        jButtonVerMozoExp = new javax.swing.JButton();
        jButtonVerPedMoz = new javax.swing.JButton();
        jButtonPedido = new javax.swing.JButton();
        jButtonMontoRecaudacion = new javax.swing.JButton();
        jLabelNombreUsuario = new javax.swing.JLabel();
        FondoVentanaPrincipal = new javax.swing.JLabel();

        RegistroMozo.setTitle("REGISTRO DE MOZOS");
        RegistroMozo.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRegistrarMozoSalir.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButtonRegistrarMozoSalir.setText("Regresar");
        jButtonRegistrarMozoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarMozoSalirActionPerformed(evt);
            }
        });
        RegistroMozo.getContentPane().add(jButtonRegistrarMozoSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("REGISTRO DE");
        RegistroMozo.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("MOZOS:");
        RegistroMozo.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        nameMesero1.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        nameMesero1.setForeground(new java.awt.Color(255, 255, 255));
        nameMesero1.setText("Nombre del Mozo: ");
        RegistroMozo.getContentPane().add(nameMesero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        nameMesero.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        nameMesero.setForeground(new java.awt.Color(255, 255, 255));
        nameMesero.setText("Años de Experiencia: ");
        RegistroMozo.getContentPane().add(nameMesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jTextFieldNombreMozo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreMozoActionPerformed(evt);
            }
        });
        jTextFieldNombreMozo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreMozoKeyTyped(evt);
            }
        });
        RegistroMozo.getContentPane().add(jTextFieldNombreMozo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 210, 30));

        jTextFieldAñosExperiencia.setPreferredSize(new java.awt.Dimension(10, 30));
        jTextFieldAñosExperiencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAñosExperienciaKeyTyped(evt);
            }
        });
        RegistroMozo.getContentPane().add(jTextFieldAñosExperiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 130, 30));

        jButtonRegisstrarMozo.setBackground(new java.awt.Color(255, 204, 204));
        jButtonRegisstrarMozo.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jButtonRegisstrarMozo.setForeground(new java.awt.Color(255, 102, 102));
        jButtonRegisstrarMozo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/usuarioingreso.png"))); // NOI18N
        jButtonRegisstrarMozo.setText("Registrar Mozo");
        jButtonRegisstrarMozo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisstrarMozoActionPerformed(evt);
            }
        });
        RegistroMozo.getContentPane().add(jButtonRegisstrarMozo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 320, 60));

        jLabelFondoResgisMozo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/JE_opt (3).jpg"))); // NOI18N
        RegistroMozo.getContentPane().add(jLabelFondoResgisMozo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 470));

        jPanel17.setBackground(new java.awt.Color(255, 153, 0));

        jButtonVerListaMozo.setText("Ver Lista Mozos");
        jButtonVerListaMozo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerListaMozoActionPerformed(evt);
            }
        });

        jTextAreaListado.setColumns(20);
        jTextAreaListado.setRows(5);
        jScrollPane1.setViewportView(jTextAreaListado);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jButtonVerListaMozo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonVerListaMozo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        RegistroMozo.getContentPane().add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 400, 480));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );

        jPanel16.setBackground(new java.awt.Color(255, 153, 153));

        jButtonVerMozoXexp.setText("Ver Mozo con Mayor Experiencia");
        jButtonVerMozoXexp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerMozoXexpActionPerformed(evt);
            }
        });

        jTextAreaVerMozoExp.setColumns(20);
        jTextAreaVerMozoExp.setRows(5);
        jScrollPane6.setViewportView(jTextAreaVerMozoExp);

        jButtonRegresarM.setText("Regresar");
        jButtonRegresarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jButtonVerMozoXexp))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonRegresarM, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonVerMozoXexp, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jButtonRegresarM, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout VerMozoXExpLayout = new javax.swing.GroupLayout(VerMozoXExp.getContentPane());
        VerMozoXExp.getContentPane().setLayout(VerMozoXExpLayout);
        VerMozoXExpLayout.setHorizontalGroup(
            VerMozoXExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VerMozoXExpLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VerMozoXExpLayout.setVerticalGroup(
            VerMozoXExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VerMozoXExpLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
            .addGroup(VerMozoXExpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 255, 102));

        jLabel7.setText("Busque mozo por Apellido: ");

        jButtonBuscarMozo.setText("Filtrar");
        jButtonBuscarMozo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarMozoActionPerformed(evt);
            }
        });

        jTableVerPedidoXMozo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "N° Plato", "Descripción", "Cantidad", "Monto Unitario"
            }
        ));
        jScrollPane2.setViewportView(jTableVerPedidoXMozo);

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setForeground(new java.awt.Color(255, 102, 102));

        jTextAreaVerListadoPedidos.setColumns(20);
        jTextAreaVerListadoPedidos.setRows(5);
        jScrollPane3.setViewportView(jTextAreaVerListadoPedidos);

        jButtonVerTodosMozos.setText("Ver Pedidos de Mozos");
        jButtonVerTodosMozos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerTodosMozosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jButtonVerTodosMozos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonVerTodosMozos)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTextFieldApellidoMozo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidoMozoActionPerformed(evt);
            }
        });

        jComboBoxVerPedidos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pedido 1", "Pedido 2", "Pedido 3", "Pedido 4", "Pedido 5", "Pedido 6" }));

        jButtonVerPlatos.setText("Ver Platos");
        jButtonVerPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerPlatosActionPerformed(evt);
            }
        });

        jButtonRegresarMe.setText("Regresar");
        jButtonRegresarMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarMeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jComboBoxVerPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonVerPlatos)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextFieldApellidoMozo, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(28, 28, 28)))
                            .addGap(49, 49, 49)
                            .addComponent(jButtonBuscarMozo)
                            .addGap(23, 23, 23)))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jButtonRegresarMe)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBuscarMozo)
                            .addComponent(jTextFieldApellidoMozo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxVerPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonVerPlatos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRegresarMe, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout VerPedidosXMozoLayout = new javax.swing.GroupLayout(VerPedidosXMozo.getContentPane());
        VerPedidosXMozo.getContentPane().setLayout(VerPedidosXMozoLayout);
        VerPedidosXMozoLayout.setHorizontalGroup(
            VerPedidosXMozoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VerPedidosXMozoLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        VerPedidosXMozoLayout.setVerticalGroup(
            VerPedidosXMozoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VerPedidosXMozoLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setPreferredSize(new java.awt.Dimension(781, 650));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(204, 255, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Pollo Enrollado");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pollo enrollado.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BoxEnrollado)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(BoxEnrollado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(204, 255, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Causa");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/causa rellena.jpg"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BoxCausa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(35, 35, 35))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BoxCausa)
                    .addComponent(jLabel17))
                .addGap(35, 35, 35))
        );

        jPanel8.setBackground(new java.awt.Color(204, 255, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Chicharron de pescado");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/chicharron pescado.jpg"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel20))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BoxPescado)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BoxPescado)
                    .addComponent(jLabel19))
                .addGap(35, 35, 35))
        );

        jPanel9.setBackground(new java.awt.Color(204, 255, 204));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Ceviche.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Ceviche.setText("Arroz con pollo");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/arroz con pollo.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(Ceviche)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BoxPollo))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BoxPollo)
                    .addComponent(Ceviche))
                .addGap(35, 35, 35))
        );

        jPanel10.setBackground(new java.awt.Color(204, 255, 204));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Ceviche1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Ceviche1.setText("Papa rellena");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/papa rellena.jpg"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Ceviche1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BoxRellena)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel10)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BoxRellena)
                    .addComponent(Ceviche1))
                .addGap(35, 35, 35))
        );

        jPanel11.setBackground(new java.awt.Color(204, 255, 204));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Ceviche2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Ceviche2.setText("Papa a la huancaina");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/huancaina.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(Ceviche2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BoxHuancaina)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ceviche2)
                    .addComponent(BoxHuancaina))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(204, 255, 204));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Ceviche3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Ceviche3.setText("Ceviche");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ceviche.jpg"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(Ceviche3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BoxCeviche))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BoxCeviche)
                    .addComponent(Ceviche3))
                .addGap(35, 35, 35))
        );

        jPanel13.setBackground(new java.awt.Color(204, 255, 204));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Ceviche4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Ceviche4.setText("Pollo a la brasa");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pollo a la brasa.jpg"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(Ceviche4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BoxBrasa1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(35, 35, 35))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BoxBrasa1)
                    .addComponent(Ceviche4))
                .addGap(35, 35, 35))
        );

        jPanel14.setBackground(new java.awt.Color(204, 255, 204));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Ceviche5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Ceviche5.setText("Lomo Saltado");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/lomo.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Ceviche5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BoxLomo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel14)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BoxLomo)
                    .addComponent(Ceviche5))
                .addGap(22, 22, 22))
        );

        AsignarMozo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AsignarMozo.setText("Siguiente");
        AsignarMozo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsignarMozoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Debes elegir solo 4 platos :)");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(228, 228, 228))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(49, 49, 49)
                .addComponent(jLabel5)
                .addGap(52, 52, 52)
                .addComponent(AsignarMozo)
                .addGap(281, 281, 281))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel5)
                    .addComponent(AsignarMozo))
                .addContainerGap())
        );

        javax.swing.GroupLayout jFramePedidoLayout = new javax.swing.GroupLayout(jFramePedido.getContentPane());
        jFramePedido.getContentPane().setLayout(jFramePedidoLayout);
        jFramePedidoLayout.setHorizontalGroup(
            jFramePedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jFramePedidoLayout.setVerticalGroup(
            jFramePedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(jTextPaneMozo);

        jLabel6.setText("Mozo Elegido:");

        jPanel18.setBackground(new java.awt.Color(153, 102, 255));
        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido"));

        jTextAreaPedido.setColumns(20);
        jTextAreaPedido.setRows(5);
        jScrollPane5.setViewportView(jTextAreaPedido);

        jButtonGuardarPedido.setText("Guardar Pedido");
        jButtonGuardarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jButtonGuardarPedido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonGuardarPedido)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jButton2)))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout ElegirMozoLayout = new javax.swing.GroupLayout(ElegirMozo.getContentPane());
        ElegirMozo.getContentPane().setLayout(ElegirMozoLayout);
        ElegirMozoLayout.setHorizontalGroup(
            ElegirMozoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ElegirMozoLayout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ElegirMozoLayout.setVerticalGroup(
            ElegirMozoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ElegirMozoLayout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Monto Recaudacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        jButtonVerMontoRecaudacion.setText("Ver Monto de Recaudacion");
        jButtonVerMontoRecaudacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerMontoRecaudacionActionPerformed(evt);
            }
        });

        jTextAreaListadoMontoRec.setColumns(20);
        jTextAreaListadoMontoRec.setRows(5);
        jScrollPane7.setViewportView(jTextAreaListadoMontoRec);

        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButtonRegresar))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jButtonVerMontoRecaudacion)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButtonVerMontoRecaudacion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jButtonRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MontoRecLayout = new javax.swing.GroupLayout(MontoRec.getContentPane());
        MontoRec.getContentPane().setLayout(MontoRecLayout);
        MontoRecLayout.setHorizontalGroup(
            MontoRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        MontoRecLayout.setVerticalGroup(
            MontoRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logout.png"))); // NOI18N
        jButtonLogout.setText("Cerrar Sesión");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, -1));

        jButtonRegistrarMozo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/coock.png"))); // NOI18N
        jButtonRegistrarMozo.setText("Registrar Mozo");
        jButtonRegistrarMozo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarMozoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegistrarMozo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 200, -1));

        jButtonVerMozoExp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/waiter_female.png"))); // NOI18N
        jButtonVerMozoExp.setText("Ver Mozo Con Más Exp");
        jButtonVerMozoExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerMozoExpActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVerMozoExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 200, -1));

        jButtonVerPedMoz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/clipboard-list.png"))); // NOI18N
        jButtonVerPedMoz.setText("Ver Pedidos Mozos");
        jButtonVerPedMoz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerPedMozActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVerPedMoz, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 200, -1));

        jButtonPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pedido_icon.png"))); // NOI18N
        jButtonPedido.setText("Hacer Pedido");
        jButtonPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 200, -1));

        jButtonMontoRecaudacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/money.png"))); // NOI18N
        jButtonMontoRecaudacion.setText("Ver Monto Recaudación");
        jButtonMontoRecaudacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMontoRecaudacionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMontoRecaudacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 200, -1));

        jLabelNombreUsuario.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabelNombreUsuario.setForeground(new java.awt.Color(255, 153, 102));
        jLabelNombreUsuario.setText("Bienvenido");
        getContentPane().add(jLabelNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, 60));

        FondoVentanaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/JE_opt (3).jpg"))); // NOI18N
        FondoVentanaPrincipal.setToolTipText("");
        FondoVentanaPrincipal.setMaximumSize(new java.awt.Dimension(600, 600));
        FondoVentanaPrincipal.setMinimumSize(new java.awt.Dimension(500, 400));
        FondoVentanaPrincipal.setPreferredSize(new java.awt.Dimension(550, 420));
        getContentPane().add(FondoVentanaPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonRegistrarMozoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarMozoActionPerformed
        // TODO add your handling code here:
        RegistroMozo.setVisible(true);
        RegistroMozo.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonRegistrarMozoActionPerformed

    private void jButtonRegistrarMozoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarMozoSalirActionPerformed
        this.setVisible(true);
        RegistroMozo.dispose();
    }//GEN-LAST:event_jButtonRegistrarMozoSalirActionPerformed

    private void jTextFieldNombreMozoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreMozoActionPerformed

    }//GEN-LAST:event_jTextFieldNombreMozoActionPerformed

    private void jTextFieldNombreMozoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreMozoKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && ((c < 'A') | c > 'Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNombreMozoKeyTyped

    private void jButtonRegisstrarMozoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisstrarMozoActionPerformed
        try {
            String apell = jTextFieldNombreMozo.getText();
            int añoE = Integer.parseInt(jTextFieldAñosExperiencia.getText());
            refM = new Mozo(apell, añoE);
            listaMozo.agregarMozoXApellido(refM);
            jTextFieldNombreMozo.setText("");
            jTextFieldAñosExperiencia.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingrese los datos correctos");
        }
    }//GEN-LAST:event_jButtonRegisstrarMozoActionPerformed

    private void jButtonVerListaMozoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerListaMozoActionPerformed
        jTextAreaListado.setText("");

        jTextAreaListado.append(listaMozo.verLista());
    }//GEN-LAST:event_jButtonVerListaMozoActionPerformed

    private void jTextFieldAñosExperienciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAñosExperienciaKeyTyped
        int k = (int) evt.getKeyChar();
        if (k >= 97 && k <= 122 || k >= 65 && k <= 90) {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
    }//GEN-LAST:event_jTextFieldAñosExperienciaKeyTyped

    private void jButtonBuscarMozoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarMozoActionPerformed

        NodoLEG<Mozo> ptr = listaMozo.obtenerMozoApe(jTextFieldApellidoMozo.getText());
        nodito = ptr;
        ArrayCola<Pedido> colita = new ArrayCola<Pedido>();

        while (ptr.getDato().getColaPedidos().colaVacia() == false) {

            colita.encolar(ptr.getDato().getColaPedidos().desencolar());

        }
        int j = 0;
        jComboBoxVerPedidos.removeAllItems();
        while (colita.colaVacia() == false) {
            Pedido refPE = colita.desencolar();
            String cadi = "Pedido " + j + 1;
            jComboBoxVerPedidos.addItem(cadi);
            ptr.getDato().getColaPedidos().encolar(refPE);
            j++;
        }


    }//GEN-LAST:event_jButtonBuscarMozoActionPerformed

    private void jButtonVerMozoExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerMozoExpActionPerformed
        jTextAreaVerMozoExp.setText("");
        VerMozoXExp.setVisible(true);
        VerMozoXExp.setLocationRelativeTo(null);
        this.dispose();


    }//GEN-LAST:event_jButtonVerMozoExpActionPerformed

    private void jButtonVerPedMozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerPedMozActionPerformed
        String[] titulo = {"NumeroPedido", "Descripcion", "Cantidad", "PrecioUnitario"};
        DefaultTableModel modelo = new DefaultTableModel(null, titulo);
        jTableVerPedidoXMozo.setModel(modelo);
        jTextAreaVerListadoPedidos.setText("");
        jTextFieldApellidoMozo.setText("");
        jComboBoxVerPedidos.removeAllItems();
        VerPedidosXMozo.setVisible(true);
        VerPedidosXMozo.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_jButtonVerPedMozActionPerformed

    private void jButtonPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPedidoActionPerformed
        BoxRellena.setSelected(false);
        BoxBrasa1.setSelected(false);
        BoxCausa.setSelected(false);
        BoxCeviche.setSelected(false);
        BoxEnrollado.setSelected(false);
        BoxHuancaina.setSelected(false);
        BoxLomo.setSelected(false);
        BoxPescado.setSelected(false);
        BoxPollo.setSelected(false);
        jFramePedido.setVisible(true);
        jFramePedido.setLocationRelativeTo(null);
        this.dispose();
        jFramePedido.setVisible(true);
        jFramePedido.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonPedidoActionPerformed

    private void AsignarMozoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsignarMozoActionPerformed
        pedido = new Pedido();
        ArrayList<Plato> platos = new ArrayList<>();

        if (BoxBrasa1.isSelected()) {
            Plato brasa = new Plato("Pollo a la Brasa");
            platos.add(brasa);

        }
        if (BoxCausa.isSelected()) {
            Plato causa = new Plato("Causa");
            platos.add(causa);
        }
        if (BoxCeviche.isSelected()) {
            Plato ceviche = new Plato("Ceviche");
            platos.add(ceviche);
        }
        if (BoxEnrollado.isSelected()) {
            Plato enrollado = new Plato("Pollo enrollado");
            platos.add(enrollado);
        }
        if (BoxHuancaina.isSelected()) {
            Plato huancaina = new Plato("Papa a la huancaina");
            platos.add(huancaina);
        }
        if (BoxLomo.isSelected()) {
            Plato lomo = new Plato("Lomos saltado");
            platos.add(lomo);
        }
        if (BoxPescado.isSelected()) {
            Plato pescado = new Plato("Chicharron de pescado");
            platos.add(pescado);
        }
        if (BoxPollo.isSelected()) {
            Plato pescado = new Plato("Arroz con pollo");
            platos.add(pescado);
        }
        if (BoxRellena.isSelected()) {
            Plato rellena = new Plato("Papa rellena");
            platos.add(rellena);

        }
        if (platos.size() == 4) {

            BoxRellena.setSelected(false);
            BoxBrasa1.setSelected(false);
            BoxCausa.setSelected(false);
            BoxCeviche.setSelected(false);
            BoxEnrollado.setSelected(false);
            BoxHuancaina.setSelected(false);
            BoxLomo.setSelected(false);
            BoxPescado.setSelected(false);
            BoxPollo.setSelected(false);

            for (Plato item : platos) {
                item.calcularCantidad();
                item.asignarPrecio();
                pedido.agregarPlato(item);

            }
            mocito = listaMozo.seleccionarMozoAleatorio().getDato();
            while (mocito.getColaPedidos().colaLlena() == true) {
                mocito = listaMozo.seleccionarMozoAleatorio().getDato();
            }
            jTextPaneMozo.setText(mocito.getApellidos());
            jTextAreaPedido.setText("");
            pedido.calcularMontoPago();
            jTextAreaPedido.setText(pedido.toString());
            ElegirMozo.setVisible(true);
            ElegirMozo.setLocationRelativeTo(null);
            jFramePedido.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Debe elegir 4 platos", "Lista Llena", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_AsignarMozoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jFramePedido.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ElegirMozo.dispose();
        jFramePedido.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonVerMozoXexpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerMozoXexpActionPerformed
        jTextAreaVerMozoExp.setText("");
        jTextAreaVerMozoExp.append(listaMozo.pedidosAños());

    }//GEN-LAST:event_jButtonVerMozoXexpActionPerformed

    private void jButtonRegresarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarMActionPerformed

        this.setVisible(true);
        VerMozoXExp.dispose();

    }//GEN-LAST:event_jButtonRegresarMActionPerformed

    private void jButtonGuardarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarPedidoActionPerformed

        listaMozo.modificarMozo(mocito.getApellidos(), pedido);

        ElegirMozo.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_jButtonGuardarPedidoActionPerformed

    private void jTextFieldApellidoMozoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidoMozoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoMozoActionPerformed

    private void jButtonVerPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerPlatosActionPerformed

        try {

            ArrayList<Pedido> listita;

            listita = listaMozo.obtenerPedidos(nodito);

            Plato[] lista = new Plato[4];

            Plato p;
            //lista=listaMozo.obtenerPlatos(listita, ptr);
            String[] cad = new String[4];

            Pedido refp = listita.get(jComboBoxVerPedidos.getSelectedIndex());
            //lista=refp.getListaPlatos();
            String[] titulo = {"NumeroPedido", "Descripcion", "Cantidad", "PrecioUnitario"};
            modelo = new DefaultTableModel(null, titulo);
            for (int i = 0; i < lista.length; i++) {

                p = refp.getListaPlatos()[i];
                cad[0] = String.valueOf(i + 1);

                cad[1] = p.getDescripcion();
                cad[2] = String.valueOf(p.getCantidad());
                cad[3] = String.valueOf(p.getPrecioUnitario());

                modelo.addRow(cad);
                jTableVerPedidoXMozo.setModel(modelo);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No hay datos asociados");
        }


    }//GEN-LAST:event_jButtonVerPlatosActionPerformed

    private void jButtonRegresarMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarMeActionPerformed

        this.setVisible(true);
        VerPedidosXMozo.dispose();

    }//GEN-LAST:event_jButtonRegresarMeActionPerformed

    private void jButtonVerTodosMozosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerTodosMozosActionPerformed

        jTextAreaVerListadoPedidos.setText("");
        jTextAreaVerListadoPedidos.append(listaMozo.retornarPedidos());


    }//GEN-LAST:event_jButtonVerTodosMozosActionPerformed

    private void jButtonVerMontoRecaudacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerMontoRecaudacionActionPerformed
        jTextAreaListadoMontoRec.setText("");
        NodoLEG<Mozo> ptr = listaMozo.getPrimero();
        if (ptr != null) {

            while (ptr != null) {
                double m = listaMozo.calcularMontoRecaudacion(ptr);

                jTextAreaListadoMontoRec.append("\nApellido: " + ptr.getDato().getApellidos()
                        + "\n    Año de experiencia: " + ptr.getDato().getAñosExperiencia()
                        + "\n    Monto recaudado: " + m + "\n");
                ptr = ptr.getSiguiente();
            }

        } else {
            JOptionPane.showMessageDialog(null, "No hay mozos registrados");
        }
    }//GEN-LAST:event_jButtonVerMontoRecaudacionActionPerformed

    private void jButtonMontoRecaudacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMontoRecaudacionActionPerformed
        jTextAreaListadoMontoRec.setText("");
        MontoRec.setVisible(true);
        MontoRec.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonMontoRecaudacionActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        this.setVisible(true);
        MontoRec.dispose();
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        BoxBrasa1.setSelected(!BoxBrasa1.isSelected());
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        BoxRellena.setSelected(!BoxRellena.isSelected());
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        BoxPescado.setSelected(!BoxPescado.isSelected());
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        BoxCausa.setSelected(!BoxCausa.isSelected());
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        BoxPollo.setSelected(!BoxPollo.isSelected());
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        BoxCeviche.setSelected(!BoxCeviche.isSelected());
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        BoxEnrollado.setSelected(!BoxEnrollado.isSelected());
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        BoxHuancaina.setSelected(!BoxHuancaina.isSelected());
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        BoxLomo.setSelected(!BoxLomo.isSelected());
    }//GEN-LAST:event_jLabel14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal(nombre).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AsignarMozo;
    private javax.swing.JCheckBox BoxBrasa1;
    private javax.swing.JCheckBox BoxCausa;
    private javax.swing.JCheckBox BoxCeviche;
    private javax.swing.JCheckBox BoxEnrollado;
    private javax.swing.JCheckBox BoxHuancaina;
    private javax.swing.JCheckBox BoxLomo;
    private javax.swing.JCheckBox BoxPescado;
    private javax.swing.JCheckBox BoxPollo;
    private javax.swing.JCheckBox BoxRellena;
    private javax.swing.JLabel Ceviche;
    private javax.swing.JLabel Ceviche1;
    private javax.swing.JLabel Ceviche2;
    private javax.swing.JLabel Ceviche3;
    private javax.swing.JLabel Ceviche4;
    private javax.swing.JLabel Ceviche5;
    private javax.swing.JFrame ElegirMozo;
    private javax.swing.JLabel FondoVentanaPrincipal;
    private javax.swing.JFrame MontoRec;
    private javax.swing.JFrame RegistroMozo;
    private javax.swing.JFrame VerMozoXExp;
    private javax.swing.JFrame VerPedidosXMozo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonBuscarMozo;
    private javax.swing.JButton jButtonGuardarPedido;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonMontoRecaudacion;
    private javax.swing.JButton jButtonPedido;
    private javax.swing.JButton jButtonRegisstrarMozo;
    private javax.swing.JButton jButtonRegistrarMozo;
    private javax.swing.JButton jButtonRegistrarMozoSalir;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JButton jButtonRegresarM;
    private javax.swing.JButton jButtonRegresarMe;
    private javax.swing.JButton jButtonVerListaMozo;
    private javax.swing.JButton jButtonVerMontoRecaudacion;
    private javax.swing.JButton jButtonVerMozoExp;
    private javax.swing.JButton jButtonVerMozoXexp;
    private javax.swing.JButton jButtonVerPedMoz;
    private javax.swing.JButton jButtonVerPlatos;
    private javax.swing.JButton jButtonVerTodosMozos;
    private javax.swing.JComboBox<String> jComboBoxVerPedidos;
    private javax.swing.JFrame jFramePedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFondoResgisMozo;
    private javax.swing.JLabel jLabelNombreUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTableVerPedidoXMozo;
    private javax.swing.JTextArea jTextAreaListado;
    private javax.swing.JTextArea jTextAreaListadoMontoRec;
    private javax.swing.JTextArea jTextAreaPedido;
    private javax.swing.JTextArea jTextAreaVerListadoPedidos;
    private javax.swing.JTextArea jTextAreaVerMozoExp;
    private javax.swing.JTextField jTextFieldApellidoMozo;
    private javax.swing.JTextField jTextFieldAñosExperiencia;
    private javax.swing.JTextField jTextFieldNombreMozo;
    private javax.swing.JTextPane jTextPaneMozo;
    private javax.swing.JLabel nameMesero;
    private javax.swing.JLabel nameMesero1;
    // End of variables declaration//GEN-END:variables
}
